#!/bin/tcsh
#***************************************************************************
#
#  HMMによるパターン認識実験用のデータの生成
#
#
#                                                   2023年10月16日 高木一幸
#
#***************************************************************************
gen 1 5000 > data1/all.txt
gen 2 5000 > data2/all.txt
cd data1
split -l 50 all.txt
cd ../
cd data2
split -l 50 all.txt
cd ..
ls data1/x?? > data1.list
ls data2/x?? > data2.list
